apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "duplicate-detector-controlller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - persistentvolumeclaims
    verbs:
      - 'create'
      - 'get'
      - 'list'
      - 'watch'
      - 'update'
      - 'patch'
      - 'delete'
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - 'create'
      - 'get'
      - 'list'
      - 'watch'
      - 'update'
      - 'patch'
      - 'delete'
  - apiGroups:
      - "com.sumologic.duplicate.detector"
    resources:
      - duplicatemessagescans
      - duplicatemessagescans/status
    verbs:
      - 'get'
      - 'list'
      - 'watch'
      - 'update'
      - 'patch'
