apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "duplicate-detector-controlller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - persistentvolumeclaims
    verbs:
      - '*'
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - "com.sumologic.duplicate.detector"
    resources:
      - singleduplicatemessagescans
      - singleduplicatemessagescans/status
    verbs:
      - '*'
