apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "duplicate-detector-controlller.labels" . | nindent 4 }}
data:
  log4j2.xml: |
    {{- .Values.log4j2 | nindent 4 }}
